import { Category } from '../types';

export const STARTER_CATEGORIES: Category[] = [
  // Top Level Categories
  {
    id: 'cat-fitness',
    parent_id: null,
    name: 'Fitness & Health',
    icon: 'Dumbbell',
    pinned: true,
    sort_order: 1,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-nutrition',
    parent_id: null,
    name: 'Nutrition',
    icon: 'Apple',
    pinned: false,
    sort_order: 2,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-learning',
    parent_id: null,
    name: 'Focused Activities',
    icon: 'Brain',
    pinned: false,
    sort_order: 4,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-life',
    parent_id: null,
    name: 'Social & Life',
    icon: 'Sun',
    pinned: false,
    sort_order: 5,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-creativity',
    parent_id: null,
    name: 'Creativity',
    icon: 'Palette',
    pinned: true,
    sort_order: 6,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-business',
    parent_id: null,
    name: 'Business & Work',
    icon: 'Briefcase',
    pinned: true,
    sort_order: 7,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-diversions',
    parent_id: null,
    name: 'Diversions',
    icon: 'Tv',
    pinned: true,
    sort_order: 8,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-home',
    parent_id: null,
    name: 'Home Projects',
    icon: 'Home',
    pinned: true,
    sort_order: 9,
    updated_at: new Date().toISOString(),
  },

  // Subcategories — Home Projects
  {
    id: 'sub-gardening',
    parent_id: 'cat-home',
    name: 'Gardening & Yard',
    icon: 'Sprout',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 1,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-diy',
    parent_id: 'cat-home',
    name: 'DIY & Repairs',
    icon: 'Hammer',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 2,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-cleaning',
    parent_id: 'cat-home',
    name: 'Organization & Cleaning',
    icon: 'Sparkles',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 3,
    updated_at: new Date().toISOString(),
  },

  // Subcategories — Diversions
  {
    id: 'sub-tv',
    parent_id: 'cat-diversions',
    name: 'Watching TV',
    icon: 'Tv',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 1,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-socialmedia',
    parent_id: 'cat-diversions',
    name: 'Social Media',
    icon: 'Smartphone',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 2,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-gaming',
    parent_id: 'cat-diversions',
    name: 'Gaming',
    icon: 'Gamepad2',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 3,
    updated_at: new Date().toISOString(),
  },

  // Subcategories — Creativity
  {
    id: 'sub-painting',
    parent_id: 'cat-creativity',
    name: 'Painting & Drawing',
    icon: 'Palette',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 1,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-writing',
    parent_id: 'cat-creativity',
    name: 'Writing',
    icon: 'Feather',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 2,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-music',
    parent_id: 'cat-creativity',
    name: 'Music & Instrument',
    icon: 'Music',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 3,
    updated_at: new Date().toISOString(),
  },

  // Subcategories — Business & Work
  {
    id: 'sub-deepwork',
    parent_id: 'cat-business',
    name: 'Deep Work',
    icon: 'Briefcase',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 1,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-meetings',
    parent_id: 'cat-business',
    name: 'Meetings',
    icon: 'Users',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 2,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-admin',
    parent_id: 'cat-business',
    name: 'Administration',
    icon: 'FolderCheck',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 3,
    updated_at: new Date().toISOString(),
  },

  // Subcategories — Fitness & Health
  {
    id: 'sub-walking',
    parent_id: 'cat-fitness',
    name: 'Walking',
    icon: 'Footprints',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 1,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-resistance',
    parent_id: 'cat-fitness',
    name: 'Resistance training',
    icon: 'Dumbbell',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 2,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-running',
    parent_id: 'cat-fitness',
    name: 'Running',
    icon: 'Activity',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 3,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-cycling',
    parent_id: 'cat-fitness',
    name: 'Cycling',
    icon: 'Bike',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 4,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-stretching',
    parent_id: 'cat-fitness',
    name: 'Stretching',
    icon: 'Smile',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 5,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-sleep',
    parent_id: 'cat-fitness',
    name: 'Sleep Time',
    icon: 'Moon',
    value_schema: { type: 'duration', unit: 'hours' },
    sort_order: 6,
    updated_at: new Date().toISOString(),
  },

  // Subcategories — Nutrition
  {
    id: 'sub-water',
    parent_id: 'cat-nutrition',
    name: 'Water',
    icon: 'Droplets',
    value_schema: { type: 'count', label: 'glasses' },
    sort_order: 1,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-meals',
    parent_id: 'cat-nutrition',
    name: 'Balanced Meals',
    icon: 'Utensils',
    value_schema: { type: 'boolean' },
    sort_order: 2,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-snacks',
    parent_id: 'cat-nutrition',
    name: 'Snacks',
    icon: 'Cookie',
    value_schema: { type: 'count', label: 'items' },
    sort_order: 3,
    updated_at: new Date().toISOString(),
  },

  // Subcategories — Learning & Mind
  {
    id: 'sub-reading',
    parent_id: 'cat-learning',
    name: 'Reading',
    icon: 'BookOpen',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 1,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-puzzles',
    parent_id: 'cat-learning',
    name: 'Crossword & Puzzles',
    icon: 'Puzzle',
    value_schema: { type: 'duration', unit: 'mins' },
    sort_order: 2,
    updated_at: new Date().toISOString(),
  },

  // Subcategories — Social & Life
  {
    id: 'sub-sailing',
    parent_id: 'cat-life',
    name: 'Sailing',
    icon: 'Anchor',
    value_schema: { type: 'count', label: 'trips' },
    sort_order: 1,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-family',
    parent_id: 'cat-life',
    name: 'Family Call',
    icon: 'PhoneCall',
    value_schema: { type: 'boolean' },
    sort_order: 2,
    updated_at: new Date().toISOString(),
  },
];
